cloudinary:
  cloud-name: delwmhc0x
  api-key: 523685645676577
  api-secret: BjXq-AeDaWkNlw6iVUuHiNamMoA

firebase:
  bucket-name: shopapi

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 86400000 #10 days
